# This CMake script wants to use libusb functionality, therefore it looks 
# for libusb include files and libraries. 
#
# Operating Systems Supported:
# - Unix (requires pkg-config)
#   Tested with Ubuntu 9.04 and Fedora 11
# - Windows (requires MinGW)
#   Tested with Windows XP/Windows 7
#
# This should work for both 32 bit and 64 bit systems.
#
# Author: F. Kooman <fkooman@tuxed.net>
#

# FreeBSD has built-in libusb since 800069
IF(CMAKE_SYSTEM_NAME MATCHES FreeBSD)
  EXEC_PROGRAM(sysctl ARGS -n kern.osreldate OUTPUT_VARIABLE FREEBSD_VERSION)
  SET(MIN_FREEBSD_VERSION 800068)
  IF(FREEBSD_VERSION GREATER ${MIN_FREEBSD_VERSION})
    SET(LIBUSB_FOUND TRUE)
    SET(LIBUSB_INCLUDE_DIRS "/usr/include")
    SET(LIBUSB_LIBRARIES "usb")
    SET(LIBUSB_LIBRARY_DIRS "/usr/lib/")
  ENDIF(FREEBSD_VERSION GREATER ${MIN_FREEBSD_VERSION})
ENDIF(CMAKE_SYSTEM_NAME MATCHES FreeBSD)

IF(NOT LIBUSB_FOUND)
  IF(WIN32)
    SET(LIBUSB_ROOT "$ENV{ProgramFiles}/libusb")
    FIND_PATH(LIBUSB_INCLUDE_DIRS libusb.h "${LIBUSB_ROOT}/include" NO_SYSTEM_ENVIRONMENT_PATH)
    IF(MINGW)
      IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
        FIND_LIBRARY(LIBUSB_LIBRARIES NAMES usb-1.0 PATHS "${LIBUSB_ROOT}/MinGW64/static" NO_SYSTEM_ENVIRONMENT_PATH)
        SET(LIBUSB_LIBRARY_DIR "${LIBUSB_ROOT}/MinGW64/dll")
      ELSE()
        FIND_LIBRARY(LIBUSB_LIBRARIES NAMES usb-1.0 PATHS "${LIBUSB_ROOT}/MinGW32/static" NO_SYSTEM_ENVIRONMENT_PATH)
        SET(LIBUSB_LIBRARY_DIR "${LIBUSB_ROOT}/MinGW32/dll")
      ENDIF()
    ELSE(MINGW)
      IF(MSVC_VERSION GREATER_EQUAL 1930)
        SET(LIBUSB_VS_DIR "VS2022")
      ELSEIF(MSVC_VERSION GREATER_EQUAL 1920)
        SET(LIBUSB_VS_DIR "VS2019")
      ELSEIF(MSVC_VERSION GREATER_EQUAL 1910)
        SET(LIBUSB_VS_DIR "VS2017")
      ELSEIF(MSVC_VERSION GREATER_EQUAL 1900)
        SET(LIBUSB_VS_DIR "VS2015")
      ELSE()
        SET(LIBUSB_VS_DIR "VS2013")
      ENDIF()
      IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
        FIND_LIBRARY(LIBUSB_LIBRARIES NAMES libusb-1.0 PATHS "${LIBUSB_ROOT}/${LIBUSB_VS_DIR}/MS64/dll" "${LIBUSB_ROOT}/${LIBUSB_VS_DIR}/MS64/static" NO_SYSTEM_ENVIRONMENT_PATH)
        SET(LIBUSB_LIBRARY_DIR "${LIBUSB_ROOT}/${LIBUSB_VS_DIR}/MS64/dll")
      ELSE()
        FIND_LIBRARY(LIBUSB_LIBRARIES NAMES libusb-1.0 PATHS "${LIBUSB_ROOT}/${LIBUSB_VS_DIR}/MS32/dll" "${LIBUSB_ROOT}/${LIBUSB_VS_DIR}/MS32/static" NO_SYSTEM_ENVIRONMENT_PATH)
        SET(LIBUSB_LIBRARY_DIR "${LIBUSB_ROOT}/${LIBUSB_VS_DIR}/MS32/dll")
      ENDIF()
    ENDIF(MINGW)
    # Must fix up variable to avoid backslashes during packaging
    STRING(REGEX REPLACE "\\\\" "/" LIBUSB_LIBRARY_DIR ${LIBUSB_LIBRARY_DIR})
  ELSE(WIN32)
    # If not under Windows we use PkgConfig
    FIND_PACKAGE (PkgConfig)
    IF(PKG_CONFIG_FOUND)
      PKG_CHECK_MODULES(LIBUSB REQUIRED libusb-1.0)
    ELSE(PKG_CONFIG_FOUND)
      MESSAGE(FATAL_ERROR "Could not find PkgConfig")
    ENDIF(PKG_CONFIG_FOUND)
  ENDIF(WIN32)
  
  IF(LIBUSB_INCLUDE_DIRS AND LIBUSB_LIBRARIES)
     SET(LIBUSB_FOUND TRUE)
  ENDIF(LIBUSB_INCLUDE_DIRS AND LIBUSB_LIBRARIES)
ENDIF(NOT LIBUSB_FOUND)

IF(LIBUSB_FOUND)
  IF(NOT LIBUSB_FIND_QUIETLY)
    MESSAGE(STATUS "Found LIBUSB: ${LIBUSB_LIBRARIES} ${LIBUSB_INCLUDE_DIRS}")
  ENDIF (NOT LIBUSB_FIND_QUIETLY)
ELSE(LIBUSB_FOUND)
  IF(LIBUSB_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find LIBUSB")
  ENDIF(LIBUSB_FIND_REQUIRED)
ENDIF(LIBUSB_FOUND)
